services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: lab8db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - '8080:8080'

volumes:
  pgdata:
