
services:
  postgres:
    image: postgres:14
    container_name: pg-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"

volumes:
  pgdata:
